site_name: mongo-migration-stream
site_description: Tool for online MongoDB migrations
site_author: allegro.tech

repo_url: https://github.com/allegro/mongo-migration-stream
edit_uri: tree/main/docs

#theme:
#  name: material
#  features:
#    - navigation.sections
#    - toc.integrate

#markdown_extensions:
#  - toc:
#      anchorlink: true

nav:
  - About the project: 'index.md'
  - Configuration: 'configuration.md'

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
